### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by Aareksio** [richiijs/autobettingbot#1]
Hey,

I'd keep 3rd statistics field as a `balance`, because it's just difference between starting and current coin amount - `profit` is not exactly the word you want to use.
Also, `@match` defines where the script works, and where it doesn't - using `csgopolygon.com`/`csgodouble.com` there allows it to run on these sites, if you put Github link there, it won't work at all.

PS. Nice catch with new domain (without `www`) on csgodouble!

**Comment by richiijs** [comment]
Hey,
With profit word all fine, because profit word are in statistic, here: http://prntscr.com/9zwuz0 
And yeah, about @match i know, all fixed. Thanks for suggestion ! :)
